//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.ModelDTO.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    [System.SerializableAttribute()]
    public partial class Product : OnlineStore.ModelDTO.ProductService.AggregateRoot {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNew {
            get {
                return this.IsNewField;
            }
            set {
                if ((this.IsNewField.Equals(value) != true)) {
                    this.IsNewField = value;
                    this.RaisePropertyChanged("IsNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AggregateRoot", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineStore.ModelDTO.ProductService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineStore.ModelDTO.ProductService.Product))]
    public partial class AggregateRoot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    [System.SerializableAttribute()]
    public partial class Category : OnlineStore.ModelDTO.ProductService.AggregateRoot {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProducts", ReplyAction="urn:IProductService/GetProductsResponse")]
        OnlineStore.ModelDTO.ProductService.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProducts", ReplyAction="urn:IProductService/GetProductsResponse")]
        System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductsForCategory", ReplyAction="urn:IProductService/GetProductsForCategoryResponse")]
        OnlineStore.ModelDTO.ProductService.Product[] GetProductsForCategory(System.Guid categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductsForCategory", ReplyAction="urn:IProductService/GetProductsForCategoryResponse")]
        System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetProductsForCategoryAsync(System.Guid categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetNewProducts", ReplyAction="urn:IProductService/GetNewProductsResponse")]
        OnlineStore.ModelDTO.ProductService.Product[] GetNewProducts(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetNewProducts", ReplyAction="urn:IProductService/GetNewProductsResponse")]
        System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetNewProductsAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetCategories", ReplyAction="urn:IProductService/GetCategoriesResponse")]
        OnlineStore.ModelDTO.ProductService.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetCategories", ReplyAction="urn:IProductService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductById", ReplyAction="urn:IProductService/GetProductByIdResponse")]
        OnlineStore.ModelDTO.ProductService.Product GetProductById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductById", ReplyAction="urn:IProductService/GetProductByIdResponse")]
        System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product> GetProductByIdAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : OnlineStore.ModelDTO.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<OnlineStore.ModelDTO.ProductService.IProductService>, OnlineStore.ModelDTO.ProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineStore.ModelDTO.ProductService.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public OnlineStore.ModelDTO.ProductService.Product[] GetProductsForCategory(System.Guid categoryId) {
            return base.Channel.GetProductsForCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetProductsForCategoryAsync(System.Guid categoryId) {
            return base.Channel.GetProductsForCategoryAsync(categoryId);
        }
        
        public OnlineStore.ModelDTO.ProductService.Product[] GetNewProducts(int count) {
            return base.Channel.GetNewProducts(count);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product[]> GetNewProductsAsync(int count) {
            return base.Channel.GetNewProductsAsync(count);
        }
        
        public OnlineStore.ModelDTO.ProductService.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public OnlineStore.ModelDTO.ProductService.Product GetProductById(System.Guid id) {
            return base.Channel.GetProductById(id);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.ModelDTO.ProductService.Product> GetProductByIdAsync(System.Guid id) {
            return base.Channel.GetProductByIdAsync(id);
        }
    }
}
